### ISSUE TITLE
cfclient error (CF-RateLimitV2APIExceeded|10018) during creation of CF space 

### ISSUE THREAD

**Issue by Fasee-khan** [SAP/cf-service-operator#24]
**Description:**
 (CF-RateLimitV2APIExceeded|10018) Error during SPACE creation

`Error requesting users: cfclient error (CF-RateLimitV2APIExceeded|10018): Rate Limit of V2 API Exceeded. Please consider using the V3 API
`

This is however reconciled after the API rate limit is reset but this creates issues during integration tests as the failure rate is high.

Current Client: github.com/cloudfoundry-community/go-cfclient/v2

Since, V2 is deprecated , could we check if we can start using go-cfclient/v3.

**Comment by dafe-corporate-sap** [comment]
it may be relevant to https://docs.cloudfoundry.org/running/setting-rate-limit-cloud-api.html#v2-api-exclude

**Comment by Fasee-khan** [comment]
The current rate limit is 1k request / user / hour 

As part of V2 depreciation , the request limit was reduced in Aug 2023 to accommodate only **3%** of API calls via V2

current X-RateLimits can be checked by `cf curl /v2/stacks -v` ( after cf login -a <api>)
 
```
X-Ratelimit-Limit-V2-Api: 1000
X-Ratelimit-Remaining-V2-Api: 900
```

I observed in the "CP CF core platform logs" that the API call statistics for the technical user responsible for creating CF spaces/instances have already exceeded the established limits. It's worth noting that this situation pertains to just a **single type of request.**

`/v2/spaces/<GUID>/developers`

having said that , the latest information is that by Q1 24 , the V2 API will be completely blocked on canary landscapes.
The Suggestion from BTP Control plan team is to migrate all calls to V3.

**Comment by cbarbian-sap** [comment]
That is, we should migrate to github.com/cloudfoundry-community/go-cfclient/v3 (currently we use v2 of that module which has only partial CF V3 support).
